name: myh_shop
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_datetime_picker: ^1.1.1
  cached_network_image: ^0.6.0+1
  shared_preferences: ^0.5.1+1
  scoped_model: ^1.0.1
  dio: ^2.0.22
  flutter_swiper: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - img/bl.png
    - img/bl2.png
    - img/logo.png
    - img/1_46.png
    - img/1_49.png
    - img/1_51_02.png
    - img/1_54.png
    - img/1_56.png
    - img/1_03.png
    - img/1_07.png
    - img/1_09.png
    - img/1_11.png
    - img/1_17.png
    - img/1_20.png
    - img/1_24.png
    - img/1_26.png
    - img/1_28.png
    - img/1_33.png
    - img/1_34.png
    - img/1_35.png
    - img/1_40.png
    - img/1_41.png
    - img/man.png
    - img/woman.png
    - img/screen.png
    - img/radio_no.png
    - img/radio_yes.png
    - img/1_003.png
    - img/1_005.png
    - img/1_007.png
    - img/1_009.png
    - img/2_01.jpg
    - img/21_04.png
    - img/21_06.png
    - img/21_08.png
    - img/21_13.png
    - img/21_14.png
    - img/21_15.png
    - img/21_19.png
    - img/21_20.png
    - img/21_21.png
    - img/21_25.png
    - img/21_26.png
    - img/3_03.png
    - img/3_06.png
    - img/3_11.png
    - img/3_14.png
    - img/5.0_16.png
    - img/5.0_19.png
    - img/5.0_22.png
    - img/5.0_27.png
    - img/5.0_28.png
    - img/5.0_29.png
    - img/5.0_33.png
    - img/5.0_34.png
    - img/5.0_35.png
    - img/5.01_01.png
    - img/2.10_01.png
    - img/2.10_04.png
    - img/2.10_07.png
    - img/2.10_10.png
    - img/coupon.png
    - img/5.2_05.png
    - img/5.21_01.png
    - img/5.3_03.png
    - img/5.3_06.png
    - img/5.1_03.png
    - img/5.1_06.png
    - img/5.1_08.png
    - img/5.1_10.png
    - img/5.1_12.png
    - img/5.1_14.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
